### PR TITLE
chore(docs): add n8n, improve markup

### PR DESCRIPTION
**Pull request by eshepelyuk**

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@bisonlou @Yann-J could you please review ?

**Comment by ievgenii-shepeliuk** [comment]
> @bisonlou @Yann-J could you please review ?
@bisonlou @Yann-J ?

**Comment by eshepelyuk** [comment]
@bisonlou @Yann-J could you plz review ?

**Review by bisonlou — APPROVED** [review]

**Comment by Yann-J** [comment]
Hey @eshepelyuk really sorry for the slow response here - we're a bit new at open-sourcing our stuff... Thanks a lot for the contribution!

**Pull request merged**
